=== GulshirinBerdiyeva/epam-java-web/task-4/src/main/resources/orangery.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/orangery"
        xmlns:tns="http://www.example.com/orangery"
        elementFormDefault="qualified">


    <element name="plant" type="tns:Plant" />
    <element name="rosacea" type="tns:Rosacea" substitutionGroup="tns:plant" />


    <element name="orangery">
            <complexType>
                    <sequence>
                        <element ref="tns:plant" minOccurs="2" maxOccurs="unbounded" />
                    </sequence>
            </complexType>
    </element>


    <complexType name="Plant">
        <sequence>
            <element name="name" type="string" />
            <element name="visual-parameters" type="tns:PlantVisualParameters" />
        </sequence>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[pr]\d{1,2}" />
                </restriction>
            </simpleType>
        </attribute>
    </complexType>


    <complexType name="PlantVisualParameters">
        <sequence>
            <element name="color" type="string" />
            <element name="floral-parts" type="positiveInteger" />
            <element name="length" type="positiveInteger" />
        </sequence>
    </complexType>

    
    <complexType name="Rosacea">
        <complexContent>
            <extension base="tns:Plant">
                <attribute name="thorns" type="boolean" use="optional" default="false" />
            </extension>
        </complexContent>
    </complexType>


</schema>

=== GulshirinBerdiyeva/epam-java-web/task-4/src/main/resources/orangery.xml
<?xml version="1.0" encoding="UTF-8" ?>
<orangery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/orangery"
          xsi:schemaLocation="http://www.example.com/orangery orangery.xsd">


    <plant id="p01">
        <name>tulip</name>
        <visual-parameters>
            <color>yellow</color>
            <floral-parts>1</floral-parts>
            <length>20</length>
        </visual-parameters>
    </plant>

    <plant id="p02">
        <name>chamomile</name>
        <visual-parameters>
            <color>blue</color>
            <floral-parts>7</floral-parts>
            <length>15</length>
        </visual-parameters>
    </plant>

    <rosacea id="r01" thorns="true">
        <name>rose</name>
        <visual-parameters>
            <color>red</color>
            <floral-parts>5</floral-parts>
            <length>50</length>
        </visual-parameters>
    </rosacea>

    <rosacea id="r02">
        <name>spirea</name>
        <visual-parameters>
            <color>white</color>
            <floral-parts>7</floral-parts>
            <length>100</length>
        </visual-parameters>
    </rosacea>

</orangery>
